import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// Shared enums
export const roleValidator = v.union(
  v.literal("CEO"),
  v.literal("Developer"),
  v.literal("Trader"),
  v.literal("Analyst"),
  v.literal("Educator"),
  v.literal("Housekeeper"),
  v.literal("Staff"),
);

export const statusValidator = v.union(
  v.literal("idle"),
  v.literal("thinking"),
  v.literal("working"),
  v.literal("in_meeting"),
);

export const roomValidator = v.union(
  v.literal("office"),
  v.literal("trading_floor"),
  v.literal("dev_room"),
  v.literal("meeting_room"),
  v.literal("classroom"),
);

export default defineSchema({
  // The AI employees. Position drives the 2D sprite on the office canvas.
  agents: defineTable({
    name: v.string(),
    role: roleValidator,
    backstory: v.string(),
    personality: v.string(),
    // Grid coordinates (tiles), not pixels — the canvas multiplies by tile size.
    x: v.number(),
    y: v.number(),
    room: roomValidator,
    status: statusValidator,
    // Sprite tint / accent color, e.g. "#ff6b6b".
    color: v.string(),
    // Latest thought/speech bubble text, if any.
    speech: v.optional(v.string()),
  }).index("by_role", ["role"]),

  // Work items the CEO delegates and other agents execute.
  tasks: defineTable({
    title: v.string(),
    description: v.string(),
    status: v.union(
      v.literal("backlog"),
      v.literal("in_progress"),
      v.literal("awaiting_approval"),
      v.literal("done"),
      v.literal("failed"),
    ),
    priority: v.union(
      v.literal("low"),
      v.literal("medium"),
      v.literal("high"),
    ),
    createdBy: v.id("agents"),
    assignedTo: v.optional(v.id("agents")),
    requiresApproval: v.boolean(),
    approved: v.boolean(),
  })
    .index("by_status", ["status"])
    .index("by_assignee", ["assignedTo"]),

  // Strict, schema-bound inter-agent messages (no free-form text between agents).
  // `payload` is a stringified JSON object validated at the call site.
  messages: defineTable({
    from: v.id("agents"),
    // null = broadcast to all agents.
    to: v.optional(v.id("agents")),
    type: v.union(
      v.literal("task_assignment"),
      v.literal("status_update"),
      v.literal("review_request"),
      v.literal("approval_request"),
      v.literal("chat"),
    ),
    payload: v.string(),
  })
    .index("by_to", ["to"])
    .index("by_from", ["from"]),

  // Per-agent simulated investment portfolio (Trader agents).
  portfolio: defineTable({
    agentId: v.id("agents"),
    cash: v.number(),
    // Stringified JSON: { position: { side, entry, sl, tp1, units, openedAt } | null }
    holdings: v.string(),
    totalValue: v.number(),
    // Realized P/L since inception.
    realizedPnl: v.optional(v.number()),
    // Latest gold signal (stringified GoldSignal) for the dashboard.
    lastSignal: v.optional(v.string()),
  }).index("by_agent", ["agentId"]),

  // Append-only audit log for governance / cascading-error tracing.
  events: defineTable({
    type: v.string(),
    actorId: v.optional(v.id("agents")),
    data: v.string(),
  }).index("by_type", ["type"]),

  // Department deliverables produced by hired Staff agents (the team feed).
  works: defineTable({
    agentId: v.id("agents"),
    name: v.string(),
    division: v.string(),
    output: v.string(),
  }),

  // Sandbox executions by Devon (code + real output from the Docker runner).
  runs: defineTable({
    taskId: v.optional(v.id("tasks")),
    agentId: v.id("agents"),
    title: v.string(),
    code: v.string(),
    stdout: v.string(),
    stderr: v.string(),
    exitCode: v.number(),
    ok: v.boolean(),
  }),

  // GAS teaching materials generated by the educator (ครูตั้ม).
  materials: defineTable({
    agentId: v.id("agents"),
    topic: v.string(),
    title: v.string(),
    codeJs: v.string(),
    indexHtml: v.string(),
  }).index("by_agent", ["agentId"]),

  // Time-series of a trader's portfolio value (one point per trade beat) for the
  // equity chart. `_creationTime` is the timestamp.
  equity: defineTable({
    agentId: v.id("agents"),
    value: v.number(),
    cash: v.number(),
  }).index("by_agent", ["agentId"]),

  // Singleton-ish control row for the simulation game loop.
  sim: defineTable({
    running: v.boolean(),
    tick: v.number(),
    // Last loop error (e.g. an LLM rate-limit), surfaced in the UI. Cleared on
    // the next successful beat.
    lastError: v.optional(v.string()),
  }),
});
